name: Simple Commands on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  run-commands:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v4

    - name: 'Run PowerShell Commands'
      shell: pwsh
      run: |
        # List directories in the current directory
        Get-ChildItem -Directory

        # Print Hello, World!
        Write-Output "Hello, World!"
